version: '2'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    #volumes:
    #  - ./kibana/.kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      XPACK_MONITORING_ENABLED: "false"
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "false"
    ports:
      - 5601:5601
    networks:
      - esnet
    links:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    command: elasticsearch -Expack.security.enabled=false
    #container_name: elasticsearch1
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet
 #   cap_add:
 #     - IPC_LOCK
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  metricbeat:
    image: athieriot/metricbeat
    #restart: unless-stopped
    pid: host
    networks:
      - esnet
    links:
      - elasticsearch
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - ./metricbeat/metricbeat.yml:/metricbeat/metricbeat.yml
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    command:
      - "-system.hostfs=/hostfs"

volumes:
  esdata1:
    driver: local

networks:
  esnet:
    driver: bridge
