version: '2'

services:
  slave:
    build: ./
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./conf.d:/conf.d
      - pgdata:/pgdata
      - pglog:/tmp
#    ports:
#      - "5433:5432"
    env_file:
     - ./../env_file
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - PGDATA=/pgdata
    networks:
      - pgnet

networks:
  pgnet:
    external: true

volumes:
  pgdata:
  pglog:
