version: '2'

services:
  kibana:
    build: ./
    #volumes:
    #  - ./kibana/.kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      XPACK_GRAPH_ENABLED: "false"
      XPACK_MONITORING_ENABLED: "false"
      XPACK_SECURITY_ENABLED: "false"
      XPACK_REPORTING_ENABLED: "false"
    ports:
      - 5601:5601
    networks:
      - esnet
    #links:
    #  - elasticsearch

networks:
  esnet:
    driver: bridge
