version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    command: elasticsearch -Expack.security.enabled=false -Expack.monitoring.enabled=false -Expack.graph.enabled=false -Expack.watcher.enabled=false
    #container_name: elasticsearch1
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet
    cap_add:
      - IPC_LOCK
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  logstash:
    build: ./logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - esnet
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    #volumes:
    #  - ./kibana/.kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      XPACK_GRAPH_ENABLED: "false"
      XPACK_MONITORING_ENABLED: "false"
      XPACK_SECURITY_ENABLED: "false"
      XPACK_REPORTING_ENABLED: "false"
    ports:
      - 5601:5601
    networks:
      - esnet
    links:
      - elasticsearch
  
  metricbeat:
    build: ./metricbeat
    networks:
      - esnet
    #links:
    #  - elasticsearch
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - ./conf:/usr/share/metricbeat/conf
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
    depends_on:
      - elasticsearch
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_URL=http://elasticsearch:9200

volumes:
  esdata1:
    driver: local

networks:
  esnet:
    driver: bridge
