version: '2'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  go:
    build: .
    links:
      - postgres:db
    ports:
      - "8080:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres?sslmode=disable
