postgres:
  image: postgres:latest
  ports:
    - "5432"
  environment:
    - POSTGRES_PASSWORD="postgres"
    - DATABASE_URL="postgresql://postgres:postgres@postgres/postgres"

go:
  build: .
  links:
    - postgres:db
  ports:
    - "8080"
