version: '2'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
        - ./:/share

  go:
    build: .
    links:
      - postgres:db
    ports:
      - "80:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/postgres?sslmode=disable
