version: '2'

services:
  master:
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
        - "15432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata

  slave:
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
        - "25432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
    links:
      - master
