version: '2'

services:
  elasticsearch:
    build: ./
    command: elasticsearch -Expack.security.enabled=false -Expack.monitoring.enabled=false -Expack.graph.enabled=false -Expack.watcher.enabled=false
    #container_name: elasticsearch1
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet
    cap_add:
      - IPC_LOCK
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

volumes:
  esdata1:
    driver: local

networks:
  esnet:
    driver: bridge
