version: '2'

services:
  elasticsearch:
    extends:
      file: ../elasticsearch/docker-compose.yml
      service: elasticsearch

  filebeat:
    extends:
      file: ../filebeat/docker-compose.yml
      service: filebeat
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /tmp/data:/mnt/data
    depends_on:
      - logstash

  logstash:
    extends:
      file: ../logstash/docker-compose.yml
      service: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch

  kibana:
    extends:
      file: ../kibana/docker-compose.yml
      service: kibana
    depends_on:
      - elasticsearch

  postgres:
    extends:
      file: ../postgres/docker-compose.yml
      service: master

#  ubuntu:
#    extends:
#      file: ../ubuntu/docker-compose.yml
#      service: ubuntu
#    links:
#      - logstash
#    networks:
#      - esnet
#    ports:
#      - "80:80"

volumes:
  esdata1:
    driver: local

networks:
  esnet:
    driver: bridge
