version: '2'

services:
  elasticsearch:
    extends:
      file: ../elasticsearch/docker-compose.yml
      service: elasticsearch

  logstash:
    extends:
      file: ../logstash/docker-compose.yml
      service: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch

  kibana:
    extends:
      file: ../kibana/docker-compose.yml
      service: kibana
    depends_on:
      - elasticsearch

  ubuntu:
    extends:
      file: ../ubuntu/docker-compose.yml
      service: ubuntu
    links:
      - logstash
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
    driver: bridge
