version: '2'

services:
  primary:
    build: ./..
    volumes:
      - ./../docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./../conf.d:/conf.d
      - ./../scripts:/scripts
      - pgdata:/pgdata
      - pglog:/tmp
    ports:
      - "5432:5432"
    env_file:
      - ./../env_file
    networks:
      - pgnet
    environment:
      - ROLE=''
      - POSTGRES_MASTER=postgres

networks:
  pgnet:
    external: true

volumes:
  pgdata:
  pglog:
