version: '2'

services:
  master:
    build: ./
    volumes:
      - pgdata_master:/pgdata
    ports:
        - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata

  slave:
    build: ./
    volumes:
      - pgdata_slave:/pgdata
    ports:
        - "5433:5433"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
    links:
      - master

volumes:
  pgdata_master
  pgdata_slave
