version: '2'

services:
  master:
    build: ./
    volumes:
      - pgdata_master:/pgdata
    ports:
        - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/pgdata

  slave:
    build: ./
    volumes:
      - pgdata_slave:/pgdata
    ports:
        - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/pgdata
    links:
      - master

volumes:
  pgdata_master:
  pgdata_slave:

networks:
  default:
    external:
      name: dockerpostgresplus_default
