version: '2'

services:
  master:
    build: ./
    extends:
      file: ./master/docker-compose.yml
      service: master

  slave:
    build: ./
    extends:
      file: ./slave/docker-compose.yml
      service: slave
    depends_on:
      - master
      

volumes:
  pgdata_master:
  pgdata_slave:
  pglog:

networks:
  default:
    external:
      name: dockerpostgresplus_default
